apiVersion: v1
kind: ConfigMap
metadata:
  name: kilo-config
  namespace: kilo-guardian
data:
  ALLOW_NETWORK: "false"
  OLLAMA_MODEL: "llama3.1:8b"
  OLLAMA_URL: "http://kilo-ollama:11434"
# K8s Deployments + Services for core kilo-guardian microservices
# NOTE: These are minimal manifests to get started. Adjust resources, probes, env and volumes per service.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kilo-gateway
  namespace: kilo-guardian
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kilo-gateway
  template:
    metadata:
      labels:
        app: kilo-gateway
    spec:
      containers:
      - name: gateway
        image: kilo/gateway:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef: {name: library-admin}
        - configMapRef: {name: kilo-config}
        readinessProbe:
          httpGet: {path: /health, port: 8000}
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet: {path: /health, port: 8000}
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests: {cpu: "100m", memory: "128Mi"}
          limits: {cpu: "500m", memory: "512Mi"}
---
apiVersion: v1
kind: Service
metadata:
  name: kilo-gateway
  namespace: kilo-guardian
spec:
  type: ClusterIP
  selector:
    app: kilo-gateway
  ports:
  - name: http
    port: 8000
    targetPort: 8000

---
# AI Brain
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kilo-ai-brain
  namespace: kilo-guardian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kilo-ai-brain
  template:
    metadata:
      labels:
        app: kilo-ai-brain
    spec:
      containers:
      - name: ai-brain
        image: kilo/ai_brain:latest
        ports:
        - containerPort: 9004
        envFrom:
        - secretRef: {name: library-admin}
        - configMapRef: {name: kilo-config}
        readinessProbe:
          httpGet: {path: /health, port: 9004}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet: {path: /health, port: 9004}
          initialDelaySeconds: 20
          periodSeconds: 30
        resources:
          requests: {cpu: "250m", memory: "512Mi"}
          limits: {cpu: "1", memory: "2Gi"}
---
apiVersion: v1
kind: Service
metadata:
  name: kilo-ai-brain
  namespace: kilo-guardian
spec:
  type: ClusterIP
  selector:
    app: kilo-ai-brain
  ports:
  - name: http
    port: 9004
    targetPort: 9004

---
# Frontend (nginx)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kilo-frontend
  namespace: kilo-guardian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kilo-frontend
  template:
    metadata:
      labels:
        app: kilo-frontend
    spec:
      containers:
      - name: frontend
        image: kilo/frontend:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet: {path: /, port: 80}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests: {cpu: "50m", memory: "64Mi"}
---
apiVersion: v1
kind: Service
metadata:
  name: kilo-frontend
  namespace: kilo-guardian
spec:
  type: ClusterIP
  selector:
    app: kilo-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80

---
# Ollama (model runner) - best-as-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kilo-ollama
  namespace: kilo-guardian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kilo-ollama
  template:
    metadata:
      labels:
        app: kilo-ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        resources:
          requests: {cpu: "500m", memory: "1Gi"}

---
# NOTE: Add similar yaml blocks for other services (meds, reminder, habits, financial, ml_engine, usb_transfer, library_of_truth, cam, voice)
# For brevity, repeat patterns above and change names/ports/images per service. Use 'kilo_<service>:latest' images.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kilo-frontend-ingress
  namespace: kilo-guardian
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: kilo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kilo-frontend
            port:
              number: 80
# Additional deployments for remaining microservices
# Use patterns similar to ai_brain deployment (image: kilo/<service>:latest)

---
# Meds
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kilo-meds
  namespace: kilo-guardian
spec:
  replicas: 1
  selector:
    matchLabels: {app: kilo-meds}
  template:
    metadata: {labels: {app: kilo-meds}}
    spec:
      containers:
      - name: meds
        image: kilo/meds:latest
        ports: [{containerPort:9001}]
        livenessProbe:
          httpGet: {path: /health, port: 9001}
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet: {path: /health, port: 9001}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests: {cpu: "100m", memory: "128Mi"}
          limits: {cpu: "500m", memory: "512Mi"}
---
apiVersion: v1
kind: Service
metadata: {name: kilo-meds, namespace: kilo-guardian}
spec:
  type: ClusterIP
  selector: {app: kilo-meds}
  ports: [{name: http, port:9001, targetPort:9001}]

---
# Reminder
apiVersion: apps/v1
kind: Deployment
metadata: {name: kilo-reminder, namespace: kilo-guardian}
spec:
  replicas: 1
  selector: {matchLabels: {app: kilo-reminder}}
  template:
    metadata: {labels: {app: kilo-reminder}}
    spec:
      containers:
      - name: reminder
        image: kilo/reminder:latest
        ports: [{containerPort:9002}]
        livenessProbe:
          httpGet: {path: /, port: 9002}
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet: {path: /, port: 9002}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests: {cpu: "100m", memory: "128Mi"}
          limits: {cpu: "500m", memory: "512Mi"}

---
apiVersion: v1
kind: Service
metadata: {name: kilo-reminder, namespace: kilo-guardian}
spec:
  type: ClusterIP
  selector: {app: kilo-reminder}
  ports: [{name: http, port:9002, targetPort:9002}]

---
# Habits
apiVersion: apps/v1
kind: Deployment
metadata: {name: kilo-habits, namespace: kilo-guardian}
spec:
  replicas: 1
  selector: {matchLabels: {app: kilo-habits}}
  template:
    metadata: {labels: {app: kilo-habits}}
    spec:
      containers:
      - name: habits
        image: kilo/habits:latest
        ports: [{containerPort:9003}]
        livenessProbe:
          httpGet: {path: /health, port: 9003}
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet: {path: /health, port: 9003}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests: {cpu: "100m", memory: "128Mi"}
          limits: {cpu: "500m", memory: "512Mi"}

---
apiVersion: v1
kind: Service
metadata: {name: kilo-habits, namespace: kilo-guardian}
spec:
  type: ClusterIP
  selector: {app: kilo-habits}
  ports: [{name: http, port:9003, targetPort:9003}]

---
# Financial
apiVersion: apps/v1
kind: Deployment
metadata: {name: kilo-financial, namespace: kilo-guardian}
spec:
  replicas: 1
  selector: {matchLabels: {app: kilo-financial}}
  template:
    metadata: {labels: {app: kilo-financial}}
    spec:
      containers:
      - name: financial
        image: kilo/financial:latest
        ports: [{containerPort:9005}]

---
apiVersion: v1
kind: Service
metadata: {name: kilo-financial, namespace: kilo-guardian}
spec:
  type: ClusterIP
  selector: {app: kilo-financial}
  ports: [{name: http, port:9005, targetPort:9005}]

---
# ML Engine
apiVersion: apps/v1
kind: Deployment
metadata: {name: kilo-ml-engine, namespace: kilo-guardian}
spec:
  replicas: 1
  selector: {matchLabels: {app: kilo-ml-engine}}
  template:
    metadata: {labels: {app: kilo-ml-engine}}
    spec:
      containers:
      - name: ml-engine
        image: kilo/ml_engine:latest
        ports: [{containerPort:9008}]

---
apiVersion: v1
kind: Service
metadata: {name: kilo-ml-engine, namespace: kilo-guardian}
spec:
  type: ClusterIP
  selector: {app: kilo-ml-engine}
  ports: [{name: http, port:9008, targetPort:9008}]

---
# USB Transfer
apiVersion: apps/v1
kind: Deployment
metadata: {name: kilo-usb-transfer, namespace: kilo-guardian}
spec:
  replicas: 1
  selector: {matchLabels: {app: kilo-usb-transfer}}
  template:
    metadata: {labels: {app: kilo-usb-transfer}}
    spec:
      containers:
      - name: usb-transfer
        image: kilo/usb_transfer:latest
        ports: [{containerPort:8006}]

---
apiVersion: v1
kind: Service
metadata: {name: kilo-usb-transfer, namespace: kilo-guardian}
spec:
  type: ClusterIP
  selector: {app: kilo-usb-transfer}
  ports: [{name: http, port:8006, targetPort:8006}]

---
# Library of Truth
apiVersion: apps/v1
kind: Deployment
metadata: {name: kilo-library, namespace: kilo-guardian}
spec:
  replicas: 1
  selector: {matchLabels: {app: kilo-library}}
  template:
    metadata: {labels: {app: kilo-library}}
    spec:
      containers:
      - name: library
        image: kilo/library_of_truth:latest
        ports: [{containerPort:9006}]
        envFrom:
        - secretRef: {name: library-admin}

---
apiVersion: v1
kind: Service
metadata: {name: kilo-library, namespace: kilo-guardian}
spec:
  type: ClusterIP
  selector: {app: kilo-library}
  ports: [{name: http, port:9006, targetPort:9006}]

---
# Camera
apiVersion: apps/v1
kind: Deployment
metadata: {name: kilo-cam, namespace: kilo-guardian}
spec:
  replicas: 1
  selector: {matchLabels: {app: kilo-cam}}
  template:
    metadata: {labels: {app: kilo-cam}}
    spec:
      containers:
      - name: cam
        image: kilo/cam:latest
        ports: [{containerPort:9007}]

---
apiVersion: v1
kind: Service
metadata: {name: kilo-cam, namespace: kilo-guardian}
spec:
  type: ClusterIP
  selector: {app: kilo-cam}
  ports: [{name: http, port:9007, targetPort:9007}]

---
# Voice
apiVersion: apps/v1
kind: Deployment
metadata: {name: kilo-voice, namespace: kilo-guardian}
spec:
  replicas: 1
  selector: {matchLabels: {app: kilo-voice}}
  template:
    metadata: {labels: {app: kilo-voice}}
    spec:
      containers:
      - name: voice
        image: kilo/voice:latest
        ports: [{containerPort:9009}]

---
apiVersion: v1
kind: Service
metadata: {name: kilo-voice, namespace: kilo-guardian}
spec:
  type: ClusterIP
  selector: {app: kilo-voice}
  ports: [{name: http, port:9009, targetPort:9009}]
apiVersion: v1
kind: Namespace
metadata:
  name: kilo-guardian
  labels:
    name: kilo-guardian
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-pdb
  namespace: kilo-guardian
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: kilo-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-brain-pdb
  namespace: kilo-guardian
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: kilo-ai-brain
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
  namespace: kilo-guardian
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kilo-gateway
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-brain-hpa
  namespace: kilo-guardian
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kilo-ai-brain
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
# Sample values to configure kube-prometheus-stack (Helm) to scrape gateway admin metrics
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'ai_brain_via_gateway'
        metrics_path: /admin/ai_brain/metrics
        static_configs:
          - targets: ['kilo-gateway.kilo-guardian.svc.cluster.local:8000']
        bearer_token_file: /etc/prometheus/secrets/gateway_admin_token
        honor_labels: true

# Alternatively, define a ServiceMonitor for the gateway service (if CRD available)
apiVersion: v1
kind: Secret
metadata:
  name: library-admin
  namespace: kilo-guardian
stringData:
  LIBRARY_ADMIN_KEY: "kilo-secure-admin-2024"
  METRICS_TOKEN: "kilo-secure-admin-2024"
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kilo-gateway-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kilo-gateway
  namespaceSelector:
    matchNames:
      - kilo-guardian
  endpoints:
    - port: http
      path: /admin/ai_brain/metrics
      honorLabels: true
      basicAuth:
        username: ""
        password: {
          name: gateway-admin-token, key: token
        }
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kilo-ai-brain-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kilo-ai-brain
  namespaceSelector:
    matchNames:
      - kilo-guardian
  endpoints:
    - port: http
      path: /metrics
      honorLabels: true
      basicAuth:
        username: ""
        password: {
          name: ai-brain-metrics-token, key: token
        }